services:
  aprsd_expporter:
    image: hemna6969/aprsd-exporter:latest
    container_name: aprsd_exporter
    ports:
        - "8080:8080"
    environment:
        - TZ=America/New_York
        - APRSD_URL=http://localhost:8001
